name       : portmidi
version    : 217
release    : 1
source     :
    - http://vorboss.dl.sourceforge.net/project/portmedia/portmidi/217/portmidi-src-217.zip : 08e9a892bd80bdb1115213fb72dc29a7bf2ff108b378180586aa65f3cfd42e0f
license    : MIT
summary    : PortMidi is a library for  real-time input and output of MIDI data using a system-independent interface.
description: |
    PortMidi is a library for software developers. It supports real-time input and output of MIDI data using a system-independent interface.
builddeps  :
    - pkgconfig(alsa)
patterns:
    - [/usr/*]
setup      : |
    %patch -Np1 < $pkgfiles/portmidi-217-cmake-libdir-java-opts.patch
    sed -i "s#/usr/local#/usr#" */CMakeLists.txt pm_python/setup.py
build      : |
    %cmake -DPORTMIDI_ENABLE_JAVA=0
    %make
install    : |
    %make_install
    ln -s /usr/lib/libportmidi.so $installdir/usr/lib/libporttime.so
